name: chat_crow
description: A new Flutter project.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  animated_text_kit: ^4.2.2
  firebase_core: ^2.21.0
  firebase_auth: ^4.12.1
  cloud_firestore: ^4.12.2
  firebase_storage: ^11.4.1
  flutter_svg: ^2.0.9
  country_picker: ^2.0.22
  flutter_riverpod: ^2.4.5
  image_picker: ^1.0.4
  pinput: ^3.0.1
  flutter_contacts: ^1.1.7+1
  uuid: ^4.2.1
  intl: ^0.18.1
  cached_network_image: ^3.3.1
  cached_video_player: ^2.0.4
  emoji_picker_flutter: ^1.6.3
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/
    - assets/svgs/
    - assets/audios/
    - assets/animations/

  fonts:
    - family: Ubuntu
      fonts:
        - asset: assets/fonts/Ubuntu-Regular.ttf
